# 指明依赖库的来源地址
#source 'https://github.com/CocoaPods/Specs.git'
# 一旦CDN报错 尽量将默认源trunk删除  pod repo remove trunk
# 说明平台是ios，版本是9.0
platform :ios , '9.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

target 'AllFunctionText' do
  #pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'IQKeyboardManager'
end
